kind = "mobile"
previewPath = "/"
title = "2026 UOA Annual Congress"
version = "1.0.0"
id = "artifacts/conference-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22516

[services.development]
run = "pnpm --filter @workspace/conference-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/conference-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/conference-app", "run", "serve" ]

[services.env]
PORT = "22516"
BASE_PATH = "/"
